# Generated by Django 5.1.4 on 2025-04-09 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TO DO', 'To Do'), ('DOING', 'Doing'), ('TEST', 'Test'), ('DONE', 'Done')], db_index=True, default='BACKLOG', max_length=10)),
                ('prioridad', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJA', 'Baja')], db_index=True, default='MEDIO', max_length=6)),
                ('fecha_entrega', models.DateField(db_index=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_entrega'],
            },
        ),
    ]
