# Generated by Django 5.1.4 on 2025-02-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TO_DO', 'To_do'), ('DOING', 'Doing'), ('TEST', 'Test')], default='BACKLOG', max_length=10)),
                ('prioridad', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJA', 'Baja')], default='MEDIA', max_length=50)),
                ('fecha_entrega', models.DateField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
